environment: development

apphost: k8s

label:
  name: aspnet3core

container:
  name: aspnet3
  pullPolicy: IfNotPresent
  image: deepakbedase/netcore
  tag: v2
  port: 80
  env: 
     - name: apiurl
       value: "http://webapirelease-service/"

replicas: 3

service:
  port: 80
  type: NodePort
