environment: development

apphost: k8s

label:
  name: aspnet3core

container:
  name: aspnet3
  pullPolicy: IfNotPresent
  image: deepakbedase/netcore
  tag: v2
  port: 80
  env:
     - name: apiurl
       value: "http://18.234.49.151:30832/api/localmachine"

replicas: 3

service:
  port: 80
  type: NodePort
